### ISSUE TITLE
Need sortBy param for submissions endpoint

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/submissions-api#124]
Endpoint:  `/submissions`

Need `sortBy` param for this endpoint, initially, it should support sort by rankings 

For more inclusive design it should use : `sortBy=key1:asc,key2:desc,key3:asc` value pattern

**Comment by callmekatootie** [comment]
We need to watch out for https://github.com/topcoder-platform/submissions-api/blob/aadc62b3b943dc21778723995618966eddecfe84/src/common/helper.js#L194 and consider it in our change

**Comment by callmekatootie** [comment]
@sushilshinde 

>  initially, it should support sort by rankings

Could you elaborate here - which attribute on the submission are you expecting the sorting to happen?

**Comment by callmekatootie** [comment]
@sharathkumaranbu Discussed with Sushil. We need to provide a generic sort parameter, one of which is the sorting based on the review summation score for a submission

**Comment by callmekatootie** [comment]
Contest launched - http://www.topcoder.com/challenge-details/30098900/?type=develop

**Comment by callmekatootie** [comment]
PR Readt: https://github.com/topcoder-platform/submissions-api/pull/127

**Comment by callmekatootie** [comment]
PR merged. Closing ticket.
