### ISSUE TITLE
Change the name of the artifact

### ISSUE THREAD

**Issue by dushyantb** [topcoder-platform/submissions-api#125]
Instead of using `typeId` for using as the name of the artifact; let's use the `name` which we are taking as a part of `request body`

```
artifact: {
        name: artifactName,
        data: zipFile
      },
      typeId: typeId
```

and we can remove the `typeId` as well; as this would be redundant after this.

cc: @cwdcwd

**Comment by callmekatootie** [comment]
Contest Launched - http://www.topcoder.com/challenge-details/30098900/?type=develop

**Comment by callmekatootie** [comment]
PR ready: https://github.com/topcoder-platform/submissions-api/pull/127

**Comment by callmekatootie** [comment]
PR merged. Closing ticket.
