### ISSUE TITLE
`/v5/submissions?challengeId=XXXX` need accept request without token

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/submissions-api#181]
Endpoint: `/v5/submissions?challengeId=XXXX`

Description: In V5 integration process we have some data removed from **challenges-api** return, like `registrants` and `submissions`

Problem: To get `submissions` we need to provide user token, but need to be allowed to get submissions when the user not logged.

**Comment by luizrrodrigues** [comment]
cc @sushilshinde

**Comment by callmekatootie** [comment]
@luizrrodrigues Couldn't you use m2m tokens in this case?

**Comment by luizrrodrigues** [comment]
@callmekatootie We going to avoid the use of m2m tokens. @sushilshinde

**Comment by sushilshinde** [comment]
@callmekatootie we don't want to share secrets with developers for their local setup. 

We are trying to make community app as dumb as possible although it has limited server code it has, we don't want to add anything new. Auth should be handled by APIs. I don't want m2m calls on the community-app server.

@mtwomey

**Comment by lakshmiathreya** [comment]
@luizrrodrigues @sushilshinde @SathyaJayabal can we close this?

**Comment by SathyaJayabal** [comment]
@lakshmiathreya , we can close this as for not logged in users we now donot show the submissions tab itself, so we do not need this update
