### ISSUE TITLE
Submissions submitted form V5 Challenge API FE does not have legacy submission id

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/submissions-api#183]
The submissions that were submitted from the V5 Challenge API FE  do not have the lagacy submission id field upadted in  the database.

This the preview of the submissions api call made form V4
<img width="846" alt="Screenshot 2020-06-26 at 4 58 53 PM" src="https://user-images.githubusercontent.com/58783823/85852567-7a3a2b80-b7ce-11ea-9199-e04cb7874d84.png">

This the preview of the submissions api call made form V5
<img width="1012" alt="Screenshot 2020-06-26 at 4 58 18 PM" src="https://user-images.githubusercontent.com/58783823/85852582-80c8a300-b7ce-11ea-9245-52f579a5d2ce.png">

This is the DB entry for a submission made from V4. Note the Legacy Submission ID field is populated. 
<img width="1579" alt="Screenshot 2020-06-24 at 1 15 29 PM" src="https://user-images.githubusercontent.com/58783823/85852652-a35abc00-b7ce-11ea-81ea-8ad374050466.png">

This is the  DB entry for a submission made from V5. Note the absence of the Legacy Submission Is field.
<img width="1562" alt="Screenshot 2020-06-23 at 5 23 42 PM" src="https://user-images.githubusercontent.com/58783823/85852705-c4bba800-b7ce-11ea-80a8-a344a291fdbb.png">

**Comment by lakshmiathreya** [comment]
Submission record seems missing in Informix db for the submission done via Beta (v5):
<img width="1651" alt="Screenshot 2020-06-26 at 5 03 17 PM" src="https://user-images.githubusercontent.com/51733042/85853339-f5501180-b7cf-11ea-8608-d85895a7a638.png">

**Comment by callmekatootie** [comment]
@dushyantb Is this the repo - https://github.com/topcoder-platform/legacy-sub-processor - that sets the legacy submission id? Or some other one...

**Comment by lakshmiathreya** [comment]
Submission record present in Informix for the Submission done via Prod (v4):
<img width="1598" alt="Screenshot 2020-06-26 at 5 05 51 PM" src="https://user-images.githubusercontent.com/51733042/85853457-2af4fa80-b7d0-11ea-8bb1-53f579a4034e.png">
<img width="1638" alt="Screenshot 2020-06-26 at 5 07 48 PM" src="https://user-images.githubusercontent.com/51733042/85853477-2f211800-b7d0-11ea-9491-06a3dee1ec78.png">

**Comment by SathyaJayabal** [comment]
@lakshmiathreya, This is a blocker and does not allow the submissions submitted from V5 to be processed further. (eg: these submissions will not be visible in OR to be reviewed etc).

**Comment by SathyaJayabal** [comment]
@callmekatootie @lakshmiathreya this issue is fixed in beta after fix for #179 
We can now see the legacy submission id populated and also see the submission in OR.
This is an example submission made from V5- (beta)
<img width="1404" alt="Screenshot 2020-07-06 at 1 38 21 PM" src="https://user-images.githubusercontent.com/58783823/86571393-f1ba4880-bf8e-11ea-9558-75dc4a5d728b.png">
