### ISSUE TITLE
Submission emails link you to old url

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/submissions-api#189]
https://github.com/topcoder-platform/community-app/issues/4632

**Comment by SathyaJayabal** [comment]
cc @callmekatootie

**Comment by callmekatootie** [comment]
I am afraid I have to close the ticket - submission api does not send any emails and you would need to check with the processor that sends them out (not sure of the repo but submission api plays no role here)

**Comment by SathyaJayabal** [comment]
cc @sushilshinde
