### ISSUE TITLE
Check for auth scopes too

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/submissions-api#19]
M2M tokens will have auth scopes and not auth roles

We need to update the code - https://github.com/topcoder-platform/submissions-api/blob/develop/app.js#L65

**Comment by cwdcwd** [comment]
@callmekatootie we should support both token types. User JWTs with `roles` and M2M JWTs with `scope`

**Comment by callmekatootie** [comment]
This has been fixed. Closing
