### ISSUE TITLE
Submissions are not reflected in OR app

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/submissions-api#211]
submission is not reflection on OR, so we are having post mortem Phase.

**Reference** 
Challenge : https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30058263 

https://monosnap.com/file/8oWBMqxFZcXICskVeC3L92NfhYpMXI 
**used user** 
Copilot : TonyJ
User : tester1234

cc @callmekatootie @SathyaJayabal

**Comment by sachin-maheshwari** [comment]
@drasticdpk please verify now.

**Comment by sachin-maheshwari** [comment]
There was legacy syncing issue, so please verify on new submission.

**Comment by coderhacker** [comment]
QA Comments: this is pass on dev env.
![image](https://user-images.githubusercontent.com/62358241/107964067-f1773680-6fce-11eb-9db1-343395e1c06e.png)
cc @drasticdpk  @lakshmiathreya

**Comment by drasticdpk** [comment]
@sachin-maheshwari closing this. Please update respective (QA Pass) label, since we don't have permission for that either please add us.

**Comment by drasticdpk** [comment]
**Verified**

![image](https://user-images.githubusercontent.com/25297859/109480893-36599d80-7aa4-11eb-95e5-ea452c0a929d.png)
