### ISSUE TITLE
Unable to make Submission 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/submissions-api#212]
**Reference** : 
![image](https://user-images.githubusercontent.com/25297859/107509479-bc33a880-6bca-11eb-85a2-c99d299aca84.png)

![image](https://user-images.githubusercontent.com/25297859/107509189-43cce780-6bca-11eb-8891-a0745492ee68.png)

**Challenge** : https://www.topcoder-dev.com/challenges/cfc3f821-64e4-4585-8fdc-744928d2bc9f?tab=registrants

**User** : tester1234/appirio123

**Comment by sachin-maheshwari** [comment]
@drasticdpk you can verify now.

**Comment by coderhacker** [comment]
QA Comments: this is pass on dev env


https://user-images.githubusercontent.com/62358241/107963830-a6f5ba00-6fce-11eb-8ccb-3da433901feb.mp4

**Comment by coderhacker** [comment]
CC @drasticdpk @lakshmiathreya

**Comment by drasticdpk** [comment]
@sachin-maheshwari closing this. Please update respective (QA Pass) label, since we don't have permission for that either please add us.

**Comment by lakshmiathreya** [comment]
@drasticdpk since it's a P0 - let close only after Prod release ...

**Comment by drasticdpk** [comment]
**Prod verified.** 
![image](https://user-images.githubusercontent.com/25297859/109481063-686aff80-7aa4-11eb-9e50-16f249e63cff.png)
![image](https://user-images.githubusercontent.com/25297859/109481156-89335500-7aa4-11eb-9282-df64c8e1c250.png)
