### ISSUE TITLE
DB to ES migration script issue

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/submissions-api#214]
Currently, the db to es migration script is not fetching all the records.

For example, in the Submission table, we have 5000+ records - yet only about 2500 - 3000 of them are being returned.

**Comment by callmekatootie** [comment]
Fix db to es script to use bulk upsert instead - https://github.com/topcoder-platform/submissions-api/blob/develop/scripts/migrateFromDBToES.js

**Comment by sachin-maheshwari** [comment]
@callmekatootie can we close this ?

**Comment by drasticdpk** [comment]
It seems this issue could not test from our end (QA) cc @sachin-maheshwari @lakshmiathreya

**Comment by sachin-maheshwari** [comment]
@drasticdpk correct, that's why i mentioned @callmekatootie.

**Comment by callmekatootie** [comment]
Closing... PAID through http://software.topcoder.com/review/actions/ViewProjectDetails?method=viewProjectDetails&pid=30168403
