### ISSUE TITLE
Unable to download submission from OR

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/submissions-api#215]
**Reference** : 
https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30058299

User : jcori/appirio123 

![image](https://user-images.githubusercontent.com/25297859/108084623-86943100-709c-11eb-988a-e5405dd7fec9.png)
![image](https://user-images.githubusercontent.com/25297859/108084658-914ec600-709c-11eb-811a-fe0732a4ea7d.png)

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya that should be existing issue, please move to appropriate git repo and assign to corresponding owner. 
Example -  https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30055234 This is old submission, which is also not downloadable. CC @mtwomey 
<img width="680" alt="Screenshot 2021-02-16 at 9 14 52 PM" src="https://user-images.githubusercontent.com/6467888/108086106-05d53500-709c-11eb-969a-2e12234d7a13.png">

**Comment by drasticdpk** [comment]
@sachin-maheshwari, 
Let me create this issue in community app repo too. Let them investigate the root cause.  After that we can close it.

**Comment by drasticdpk** [comment]
Moved this ticket  to https://github.com/topcoder-platform/tc-online-review
