### ISSUE TITLE
Multiple submissions for development challenge.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/submissions-api#231]

**Comment by drasticdpk** [comment]
Verification file : https://docs.google.com/spreadsheets/d/1snA3TU1iYjkRjIDYv0dTKI6P55l9K69J2LiaHq-WmlQ/edit?usp=sharing

**Comment by drasticdpk** [comment]
Note ,
Hello Team, 
Originally this issue was raised at https://github.com/topcoder-platform/legacy-submission-processor/issues/4#issuecomment-799090674

**Comment by lakshmiathreya** [comment]
This Issue records the resolution post revert of Legacy submission processor.
