### ISSUE TITLE
Filetype is a constant

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/submissions-api#28]
@BadalZ @cwdcwd We are currently setting the file type of the file passed when creating a submission to zip.

Question: Is that ok or do we need to infer the file type from the uploaded file and that it will not always be a zip?

**Comment by cwdcwd** [comment]
good question. I think we should default to zip if we can't figure out what it is. I'm 50/50 on if we should strictly allow only zip files or not.
CC @ajefts for any opinion there.

**Comment by callmekatootie** [comment]
Related PR - https://github.com/topcoder-platform/submissions-api/pull/29

- If a submission is created by passing a file, everything is fine
- If a submission is created by passing a url, file type is not known. Due to this, submission processor faces issues.
- Setting file type to zip for now when a url is passed during submission creation.
