### ISSUE TITLE
Tie Review and ReviewSummation for easy filtering

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/submissions-api#35]
We need to find a way to perform advanced filtering on the GET `/submissions` endpoint, such as get all reviews and submissions for a contest.

Currently, that would require us to make multiple api calls. Instead, we need to use ES capabilities and try to retrieve this information in a single database read

**Comment by sharathkumaranbu** [comment]
@callmekatootie @cwdcwd Is it ok to have nested filters like `review.score=92`? This will make the ES filter code generic

**Comment by callmekatootie** [comment]
@sharathkumaranbu For now, filters that support the following will do. We can add later:

- find all submissions for a contest
- find all reviews for the contest
- find submission for a specific member
