### ISSUE TITLE
GET /submissions/{submissionId} behaviour

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/submissions-api#4]
Swagger spec asks to restrict this endpoint to only members with roles user, admin and copilot.

We need to add additional checks on the role "user" - at the moment, OR only allows members that submitted and received a passing score to access other user's submissions

**Comment by callmekatootie** [comment]
Below is applicable only to user's with access `Topcoder user`. [Relevant Code](https://github.com/topcoder-platform/submissions-api/blob/develop/src/routes/SubmissionRoutes.js#L27)

The task would be:

- When a request arrives for GET `/submissions/:submissionId`, get the submission. Let's call this submission A. Make a note of `challengeId`
- Now, get the authenticated user's `memberId` through the auth token and proceed to get the submission of the user for the same `challengeId` noted earlier. Just the `submissionId` of the retrieved submission is needed. Let's call this submission B
- Use the `submissionId` of submission B to get the `aggregateScore` of this submission through the `ReviewSummation` resource. If none exists yet, then respond with 403 Forbidden http status code for the original request. If the submission exists, and the aggregate score is more than 80, then respond with submission A for the original request.

@cwdcwd @BadalZ Does the above sound good?

**Comment by callmekatootie** [comment]
One issue here would be that different scorecards have different passing scores. Perhaps we use `isPassing` on ReviewSummation instead of aggregate score to distinguish who is allowed to access other user's submissions...

**Comment by cwdcwd** [comment]
@callmekatootie that works.
We need, at a minimum, the user check in before Thursday so please expedite this one

**Comment by callmekatootie** [comment]
We need to update tests as well here.

**Comment by sharathkumaranbu** [comment]
Also, In F2F challenges, Other member submissions are not accessible in the current OR

**Comment by callmekatootie** [comment]
I am not sure about the other points. Re: Appeal Response phase end, I am guessing that `isPassing` is set to true on the review summation only at the end of the appeals response phase?

**Comment by sharathkumaranbu** [comment]
Yeah, I believe reviewSummation will be created only after end of appeals response phase

**Comment by cwdcwd** [comment]
so if a reviewer is assigned to a challenge then I believe it should show up on an authenticated call to the challenge resources endpoint, ie: 

- `http://api.topcoder.com/v3/challenges/30069749/resources` 
- `http://api.topcoder.com/v3/challenges/30069831/resources`

 Appeals Response, and other times, should be findable on the phases endpoint. ie: 

-`http://api.topcoder.com/v3/challenges/30069749/phases`
- `http://api.topcoder.com/v3/challenges/30069831/phases`

**Comment by callmekatootie** [comment]
Which token to use with the above endpoints? I used a m2m token and got an error...

**Comment by cwdcwd** [comment]
try with your user JWT

**Comment by sharathkumaranbu** [comment]
@cwdcwd Is it valid to configure user token to access the challenge resources?

Which user token will we use in this scenario?

How about identifying challenge type? F2F challenges doesn't allow other User neither to see the score card or to download the submission.

**Comment by sharathkumaranbu** [comment]
Also I tried the above end point for a challenge I registered with my JWT token, It throws 403

**Comment by sharathkumaranbu** [comment]
@callmekatootie I tried using my JWT token for a challenge in which I was assigned as a reviewer. But even in that challenge, resources end point returned 403.

I believe resources are available only for Copilot or Administrator role not for other users. Only Copilot / Administrator can see the reviewers assigned to the challenge, observers of the challenge, etc..

Reviewers don't have such access.

**Comment by callmekatootie** [comment]
Ah yes. Makes sense. Let me see what we can do here

**Comment by sharathkumaranbu** [comment]
Just a note from current OR scenarios

1. In challenges with screening phase like UI Prototype, Assembly - If the User have passed Screening, he or she can download the winning submission even if they have failed Review

2. In F2F challenges, one member cannot download the submission of another member even if the member is the winner of the F2F (Member can't even see the scorecard of the another member)

3. In Code challenge, in the current scenario, any body who makes a submission are able to download the winning submission. Even if the submission have got score of 0/100, the member can download others submission.

This seems to be like a bigger bug. But passing Review should not be a mandate to download winning submission. Many submitters learn from winning submission. If the submitter had put efforts but not able to pass the review, the member can very well learn from winning submission.

In UI Prototype / Assembly, Screening phase will take care of this. Whether the submitter have put actual efforts or if the submission is just dummy.

If the submission passes screening, User can download the submission which is ideally valid, In Code challenges since there is no screening, it's letting all members who have made the submission to download other member submissions.

**Comment by callmekatootie** [comment]
@cwdcwd This needs some love.

**Comment by BadalZ** [comment]
As per discussion with CWD,

1. get all details for a Challenge using challenge API.
2. Retrieve type, phase and all registrants for that Challenge 
3. Get User details from its JWT

We should be able to build a logic (set of rules that Sharath has mentioned) using these data.

@callmekatootie @sharathkumaranbu

**Comment by sharathkumaranbu** [comment]
Hi,

I would need M2M token with appropriate scopes to fetch resources details from Challenge API.

Please share the corresponding Auth0 credentials in Slack.

**Comment by sharathkumaranbu** [comment]
Also we would need some discussion on Screening criteria for Users in Code track.

Since there is no screening in Code track, even User with Score 0 can download a submission now in OR.

**Comment by cwdcwd** [comment]
ok. I'll get the challenge API to accept M2M tokens and create some scopes specifically for challenge calls. Can we stub that out in the meantime while I get that done and pretend we have that and just use the `tonyj` user token from the dev environment? 

On the Code track and winning subs being available to all, is that a problem?

**Comment by sharathkumaranbu** [comment]
IMHO, Winning submission need to be available for others who make a valid submission. Submitters who have made invalid submission like empty file, dummy submissions should not gain access to winning submissions. In Assembly and UI Prototype, We have screening phase to take care of such submissions but it's not the case with Code track

**Comment by callmekatootie** [comment]
Resuming this one - we now have m2m token support for challenge api.

I have asked @sharathkumaranbu to proceed with the checks they mentioned earlier. Additionally, I have asked him to prevent members that did not get a passing score from accessing other member's submissions.

**Comment by sharathkumaranbu** [comment]
Related PR - https://github.com/topcoder-platform/submissions-api/pull/75

Challenge API has some issues with M2M token.

E.g.

The request `GET / https://api.topcoder-dev.com/v3/challenges?filter=id={challengeId}` seems to work without Authorization header but when we add Authorization header with M2M token below error is thrown

```
{
    "id": "44bf664b:1665a3f5746:-7d52",
    "result": {
        "success": true,
        "status": 400,
        "metadata": null,
        "content": "Unable to get groups from the API, the returned status code is: 500"
    },
    "version": "v3"
}

**Comment by callmekatootie** [comment]
@sharathkumaranbu They have fixed the issue with challenge api and m2m token. Can you check and confirm?

**Comment by sharathkumaranbu** [comment]
@callmekatootie Yes. It seems to be fine now. I will update the PR shortly

**Comment by callmekatootie** [comment]
Closing ticket. PR merged.
