### ISSUE TITLE
M2M token handling

### ISSUE THREAD

**Issue by sharathkumaranbu** [topcoder-platform/submissions-api#42]
Right now createdBy / updatedBy will be set only for User JWT tokens.

For M2M token, it will be set as null since authUser.handle is undefined. In case of M2M tokens, it should be set to `machine`

Created issue based on discussion with @cwdcwd

**Comment by cwdcwd** [comment]
thanks @sharathkumaranbu 
if you could resolve elegantly, that would be much appreciated

**Comment by sharathkumaranbu** [comment]
@cwdcwd Sure. :) https://github.com/topcoder-platform/submissions-api/pull/43

**Comment by cwdcwd** [comment]
@callmekatootie FYI for payment when you're back online

**Comment by cwdcwd** [comment]
@sharathkumaranbu I had an idea. I think, for M2M tokens, instead of the 'machine' constant we should set it to the value of the JWT's `sub` field. This is the 'subject' of the M2M token and will likely be unique per service and properly identifiable

**Comment by sharathkumaranbu** [comment]
@cwdcwd Fine. I will update accordingly

**Comment by cwdcwd** [comment]
thanks!
