### ISSUE TITLE
Adjustment of phaseId selection

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/submissions-api#45]
Get the phases from the challenge end point as we currently do but then:

- loop phases
- if "checkpoint" phase is open, kick out of loop & use that id. checkpoint takes priority over regular "submission" phase
- continue: if "submission" phase is open kick out and use that id
- default to null if neither are found

**Comment by cwdcwd** [comment]
@sharathkumaranbu could you take this one on?

**Comment by sharathkumaranbu** [comment]
@cwdcwd Sure

**Comment by cwdcwd** [comment]
excellent. thanks so much
