### ISSUE TITLE
Name downloaded files with submission ID

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/submissions-api#57]
When submissions are downloaded, the naming convention should be <<submission_id>>.zip.  This helps the copilots identify which downloads pertain to which submissions for a given challenge.

**Comment by ajefts** [comment]
fyi @cwdcwd

**Comment by sharathkumaranbu** [comment]
@ajefts Currently we use submissionId (UUID) generated by the application to store the files in S3 bucket. In OR, we use `legacySubmissionId` for downloading submissions and filling score card.

Shouldn't the renaming be happening at OR while downloading files from S3 bucket?

**Comment by cwdcwd** [comment]
should be resolved on 4ae0b4f24ee1a08858270942e9d56ff0297d87a6
