### ISSUE TITLE
Submission sometimes misses the Phase Id and doesnt generate the submission in OR

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/submissions-api#58]
The submission Ids have phase Id blank
f6c9344e-a7ba-4e5e-8f30-038b492c38f0	
e0ac90de-7e1b-4227-95f5-2c813c5f6d1c

cc @cwdcwd

**Comment by RiteshTC** [comment]
cc @ajefts

**Comment by cwdcwd** [comment]
I think this is a resolved issue on the Community App upload page. closing
