### ISSUE TITLE
The Api accepts the submission when the submission phase is closed

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/submissions-api#60]
Api silently ignores the submission, if the submission phase is closed.
Ideally it should throw error, notifying the submission phase is closed and submission cannot be made.

Exception should be made for admin role, to allow admins to upload submissions on user behalf.

**Comment by RiteshTC** [comment]
cc @ajefts @cwdcwd

**Comment by cwdcwd** [comment]
@callmekatootie can you have some one take a look at this one?

**Comment by callmekatootie** [comment]
Confirming that this works as intended now - the app will let the caller know that submission phase is not open, so they cannot submit (submission phase could be closed, or it might still not have opened - in either case it will give error)
