### ISSUE TITLE
Final Fix download in OR not working

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/submissions-api#64]
I think we need to update this controller if we haven't already:  https://software.topcoder-dev.com/review/actions/DownloadFinalFix?uid=317442

This is used to download a final fix, and it's currently throwing an error page in dev.

**Comment by ajefts** [comment]
@BadalZ @cwdcwd fyi

**Comment by cwdcwd** [comment]
closing this as it doesn't pertain top this repo
