### ISSUE TITLE
If a contest is in final fix phase, then only winner should be allowed to post a submission

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/submissions-api#70]
Title says it all.

Conversely, only in submission phase and final fix phase, we should allow submissions to be posted.

The winner is listed on the challenge details itself and the phase from the challenge API's /phases endpoint.

**Comment by BadalZ** [comment]
@callmekatootie  / @sharathkumaranbu  Make sure to use M2M while calling challenge API

**Comment by sharathkumaranbu** [comment]
@callmekatootie `Conversely, only in submission phase and final fix phase, we should allow submissions to be posted.`

Administrators may upload the submission after the closure of submission phase. In such case `submissionPhaseId` will be NULL. There is no check for Administrators.

Is it ok to reject a submission which doesn't have submissionPhaseId  and submission made by a user with role `Topcoder User`?

If submissionPhaseId is present, we will further check the access of the User. Like winners for Final Fix and registrants check for Submission phase.

**Comment by callmekatootie** [comment]
> Is it ok to reject a submission which doesn't have submissionPhaseId and submission made by a user with role Topcoder User?

Yes

> If submissionPhaseId is present, we will further check the access of the User. Like winners for Final Fix and registrants check for Submission phase.

Correct
