### ISSUE TITLE
Winners not shown in challenge page!

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/submissions-api#81]
In Direct, all three winners are selected but only the first winner is visible on the winner's page
https://www.topcoder.com/challenges/30072165/?type=design&ta=winners

Please check and fix the issue.

![image 2](https://user-images.githubusercontent.com/34749364/47354078-5eb67d80-d6db-11e8-98bc-be38c09c4d80.png)
![image 3](https://user-images.githubusercontent.com/34749364/47354089-637b3180-d6db-11e8-8cb2-cd1fe1761d33.png)

**Comment by callmekatootie** [comment]
@JayaDhaka I am not sure if this is the right repo for the issue.

**Comment by RiteshTC** [comment]
@callmekatootie 
This error seems to coming after the new submission api has been deployed
Prize_id  on submissions table is not populated for design submissions beyond the 1st one. Most likely the submission process is not writing back or in the format expected by the downline process

**Comment by JayaDhaka** [comment]
Here is the list of some design challenges in which all 3 winners are not visible:
https://www.topcoder.com/challenges/30070635/?type=design&tab=winners 
https://www.topcoder.com/challenges/30068825?tab=winners
https://www.topcoder.com/challenges/30070046?tab=winners 
https://www.topcoder.com/challenges/30068824?tab=winners

**Comment by cwdcwd** [comment]
@JayaDhaka @RiteshTC this would be an issue with the Community App not pulling submissions properly. I think there's actually a ticket for this already

**Comment by cwdcwd** [comment]
I believe [this is the one](https://github.com/topcoder-platform/community-app/issues/1252)

**Comment by RiteshTC** [comment]
@cwdcwd 
I don't think its an issue with the community app.
Prize Id should be populated in the submission table, for the submission to show up as winning submission.

In design challenges, submission table only the first winner is assigned the prize_id. Rest of 2nd and 3rd place winners have prize id as null.
