### ISSUE TITLE
OR cannot handle multiple submissions in final fixes phase

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/submissions-api#82]
OR doesn't close the phase, when there are multiple final fixes uploaded by the user.

**Comment by callmekatootie** [comment]
@RiteshTC This would not be the right repo for it. (I don't know if there's a repo for OR specific stuff or if its just community app).

**Comment by RiteshTC** [comment]
This is happening after the new change in submission api

**Comment by callmekatootie** [comment]
I see. In which case, I think I think the issue is with something that is consuming the submission api. They need to tell us what we are doing wrong or if its something probably at their end itself.

Not sure where we would start looking - @cwdcwd thoughts?

**Comment by cwdcwd** [comment]
tbh this sounds like an OR deficiency. Can we move this over to [here](https://github.com/topcoder-platform/tc-online-review) and I can have @coderReview dig in on it

**Comment by callmekatootie** [comment]
Done - https://github.com/topcoder-platform/tc-online-review/issues/57
