### ISSUE TITLE
Get Reviews associated with submission for workflow when fetching data from Dynamodb

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/submissions-api#83]
[Reference](https://github.com/topcoder-platform/submissions-api/blob/develop/src/services/SubmissionService.js#L76).

Reference above is pointing to code where we read data off dynamodb if ES does not have the data.

The scenario involving ES is that it gets the associated reviews for a submission, but the same does not happen in this case, when we get the submission from dynamodb.

We need to basically get the associated reviews for a submission when fetching the data from dynamodb

**Comment by callmekatootie** [comment]
@sharathkumaranbu Interested in taking this one up asap?

**Comment by sharathkumaranbu** [comment]
@callmekatootie Sure. I am just thinking about the way to do it. Because Dynamo DB support retrieval of records based on ID only. In Review table, Submission ID is not the key, Review table will have its own key.

**Comment by callmekatootie** [comment]
Tagging @cwdcwd if he has something to add.

**Comment by cwdcwd** [comment]
let's add a Global Secondary Index key on reviews so we can look up via submission Id

**Comment by cwdcwd** [comment]
my thought was we could just add another db call to `function * _getSubmission (submissionId) ` to pull that review array in

**Comment by cwdcwd** [comment]
thanks @sharathkumaranbu !

**Comment by sharathkumaranbu** [comment]
@cwdcwd We need to use a index name in the code to query records. For review and reviewSummation we will need two index names.

Should I need to make the index names as 2 config variables or 2 constants?

Also, Please note that AWS charges $ 0.59 / month per index per read or write capacity unit

**Comment by cwdcwd** [comment]
I'm fine with something like `reviewSummation-index` and `review-index`.
not concerned about cost =)

**Comment by sharathkumaranbu** [comment]
is it a configuration variable or constant in the constants.js? We are indexing submissionId in 2 tables. Hence index name `submissionId-index` could be better too

**Comment by cwdcwd** [comment]
I think constant is fine, right?

**Comment by sharathkumaranbu** [comment]
Indeed but I wanted a confirmation :)

**Comment by cwdcwd** [comment]
should we update this to add the indices? https://github.com/topcoder-platform/submissions-api/blob/develop/scripts/createTables.js

**Comment by sharathkumaranbu** [comment]
We need to update the models (https://github.com/topcoder-platform/submissions-api/tree/develop/src/models) not the createTable script.

**Comment by cwdcwd** [comment]
ahh ok
