### ISSUE TITLE
Expand Review and ReviewSummation to hold metadata

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/submissions-api#87]
Expand Review and ReviewSummation to hold a new, optional metadata object. The purpose of this member is for review and scoring services to augment the review with extra data

**Comment by cwdcwd** [comment]
@sharathkumaranbu are you interested in this one?

**Comment by callmekatootie** [comment]
PR is ready for merge - https://github.com/topcoder-platform/submissions-api/pull/88
