### ISSUE TITLE
Submissions are not reflecting for any submission

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/submissions-api#93]
Submissions are not reflecting for any type in OR

<img width="1028" alt="screen shot 2018-11-26 at 5 25 15 pm" src="https://user-images.githubusercontent.com/683231/49012727-518c2300-f1a0-11e8-8eb1-ba1fe6db0a22.png">

**Comment by sushilshinde** [comment]
@ajefts @cwdcwd comments

**Comment by callmekatootie** [comment]
Is there an example in dev instance?

**Comment by sushilshinde** [comment]
@callmekatootie 

These are two examples, actually, none of the submissions are reflecting but UI console there is no error.

**Code Type**
https://test-community-app.topcoder-dev.com/challenges/30054164

**Direct MM** 
https://test-community-app.topcoder-dev.com/challenges/30054163


I did check submission API v5 logs there is no error on the logs.

![screen shot 2018-11-27 at 3 16 58 pm](https://user-images.githubusercontent.com/683231/49073120-b8b8de80-f257-11e8-8306-9008dc8accb5.png)

FYI... @cwdcwd

**Comment by callmekatootie** [comment]
Discussed on slack. Submission api does seem to return all submissions, for both contests.

It appears that the issue lies in OR and not submission api.

**Comment by sushilshinde** [comment]
@callmekatootie you are right. 

I tested on production. submissions are reflected. Probably some issue on dev box.
